spring.jms.listener.auto-startup=true
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=artemis
spring.activemq.password=artemis
azure.cosmos.uri=https://tunequestmusicdb.documents.azure.com:443/
azure.cosmos.key=nCuWTRgCsi3ZINXCkJj9i9HWMzEFTvNZY6g5Ul3JZkFsHE3r6PLdycqeJV8XgdGCYOZpX5xlMK3vACDbCWwdMg==
azure.cosmos.database=tunequestmusicdb
azure.cosmos.populate-query-metrics=true